"""V-column reduction for the strong tabular baseline (B5).

V1-V339 are masked Vesta features with heavy redundancy. Columns are grouped by their exact
missing-value pattern; inside a group, columns linked by |r| > threshold form connected
clusters, and each cluster keeps one column (the one with the most distinct values; lowest
V number on ties). Fitted on the training period only. The result is written to
experiments/configs/v_columns.yaml so the feature set is explicit and versioned.

Run:  python -m vaultic.features.vreduce
"""

from __future__ import annotations

import argparse
import hashlib
import re
from pathlib import Path

import numpy as np
import pandas as pd
import yaml

from vaultic.data.load import load_merged
from vaultic.data.splits import load_splits
from vaultic.paths import CONFIG_DIR, MERGED_PATH

V_COLUMNS_PATH = CONFIG_DIR / "v_columns.yaml"
THRESHOLD = 0.75


def v_columns(columns) -> list[str]:
    return sorted((c for c in columns if re.fullmatch(r"V\d+", c)), key=lambda c: int(c[1:]))


def missing_pattern_groups(df: pd.DataFrame, cols: list[str]) -> list[list[str]]:
    """Columns with an identical missing-value mask, in V order."""
    groups: dict[str, list[str]] = {}
    for col in cols:
        mask = np.packbits(df[col].isna().to_numpy())
        groups.setdefault(hashlib.sha1(mask.tobytes()).hexdigest(), []).append(col)
    return list(groups.values())


def _clusters(corr: np.ndarray, threshold: float) -> list[list[int]]:
    """Connected components of the graph with an edge where |r| > threshold."""
    n = len(corr)
    parent = list(range(n))

    def find(i: int) -> int:
        while parent[i] != i:
            parent[i] = parent[parent[i]]
            i = parent[i]
        return i

    for i in range(n):
        for j in range(i + 1, n):
            if abs(corr[i, j]) > threshold:
                parent[find(i)] = find(j)
    comps: dict[int, list[int]] = {}
    for i in range(n):
        comps.setdefault(find(i), []).append(i)
    return list(comps.values())


def reduce_v(train: pd.DataFrame, threshold: float = THRESHOLD) -> dict:
    cols = v_columns(train.columns)
    kept: list[str] = []
    clusters_out = []
    for group in missing_pattern_groups(train, cols):
        values = train[group].astype(np.float64)
        if len(group) == 1:
            corr = np.ones((1, 1))
        else:
            # rows where the group is present (identical masks: all or none present)
            present = values.dropna()
            corr = present.corr().to_numpy() if len(present) > 1 else np.eye(len(group))
            corr = np.nan_to_num(corr, nan=0.0)  # constant columns correlate with nothing
        uniques = values.nunique()
        for comp in _clusters(corr, threshold):
            members = [group[i] for i in comp]
            rep = max(members, key=lambda c: (uniques[c], -int(c[1:])))
            kept.append(rep)
            clusters_out.append({"keep": rep, "members": members})
    kept = sorted(kept, key=lambda c: int(c[1:]))
    return {
        "threshold": threshold,
        "fitted_on": "train period",
        "n_input": len(cols),
        "n_kept": len(kept),
        "keep": kept,
        "clusters": sorted(clusters_out, key=lambda c: int(c["keep"][1:])),
    }


def load_kept(path: Path = V_COLUMNS_PATH) -> list[str]:
    return yaml.safe_load(Path(path).read_text(encoding="utf-8"))["keep"]


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--out", type=Path, default=V_COLUMNS_PATH)
    args = parser.parse_args()
    splits = load_splits()
    df = load_merged(MERGED_PATH)
    train = df[splits.train.contains(df["day"])]
    result = reduce_v(train)
    header = (
        "# Generated by `python -m vaultic.features.vreduce` from the TRAIN period only.\n"
        "# V columns grouped by missing-value pattern; one kept per |r| > threshold cluster.\n"
    )
    args.out.write_text(header + yaml.safe_dump(result, sort_keys=False), encoding="utf-8")
    print(f"kept {result['n_kept']} of {result['n_input']} V columns -> {args.out}")


if __name__ == "__main__":
    main()
